version: '3.9'
services:
  app:
    build: ./web
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  celery-beat:
    build: ./web
    entrypoint: celery
    command: -A celery-app.celery beat --loglevel=info
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
  celery-worker:
    build: ./web
    entrypoint: celery
    command: -A celery-app.celery worker --loglevel=DEBUG
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis